from __future__ import annotations

from danfse.rules.models.formatted import FormattedDanfse

def expected_nota_gov_1_29154166000144() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '23/02/2026',
                   'data_hora_emissao_dps': '23/02/2026 16:51:42',
                   'data_hora_emissao_nfse': '23/02/2026 16:51:42',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': None,
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '29.154.166/0001-44',
               'email': 'cccpfiscal@hotmail.com',
               'endereco': '-',
               'inscricao_municipal': '152794',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': 'Regime de apuração dos tributos federais e municipal pelo SN',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Optante - Microempresa ou Empresa ...',
               'telefone': '8235213576'},
 'servico': {'codigo_nbs': '114021100',
             'codigo_tributacao': '170101 - Assessoria ou consultoria de qualquer natureza, não contida em outros '
                                  'itens desta\n'
                                  '            lista.',
             'descricao_servico': '00103/26 AE 409051 Item 0001',
             'descricao_tributacao': 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens '
                                     'desta\n'
                                     '            lista.',
             'local_prestacao': 'Arapiraca'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': 'ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '30210',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '20,10',
            'valor_liquido_nfse': '979,90',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '1.000,00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '2,01%',
                          'base_calculo_issqn': '1.000,00',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Arapiraca',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '20,10'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '1.000,00'},
 'watermark': ''})

def expected_nota_gov_1_33762922000195() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '12/03/2026',
                   'data_hora_emissao_dps': '12/03/2026 16:35:01',
                   'data_hora_emissao_nfse': '12/03/2026 16:35:01',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': None,
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '33.762.922/0001-95',
               'email': 'CARVALHOCONTABILIDADE001@GMAIL.COM',
               'endereco': '-',
               'inscricao_municipal': '-',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': 'Regime de apuração dos tributos federais e municipal pelo SN',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Optante - Microempresa ou Empresa ...',
               'telefone': '8299301159'},
 'servico': {'codigo_nbs': '-',
             'codigo_tributacao': '171101 - Organização de festas e recepções.',
             'descricao_servico': 'Serviço e Fornecimento de Alimentação, Almoço!',
             'descricao_tributacao': 'Organização de festas e recepções.',
             'local_prestacao': 'Pão de Açúcar'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2702405 / 57.480-000',
             'documento': '12.517.413/0004-70',
             'email': '-',
             'endereco': 'PRESIDENTE CASTELO BRANCO, nº 60, BLOCO F LOJA 01 ANEXO SHOPPING DA VILA -...',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '-',
            'valor_liquido_nfse': '43,00',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '43,00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '-',
                          'base_calculo_issqn': '-',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Pão de Açúcar',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Não Retido',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '-'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '43,00'},
 'watermark': ''})

def expected_nota_gov_1_39549075000161() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '20/02/2026',
                   'data_hora_emissao_dps': '20/02/2026 15:17:37',
                   'data_hora_emissao_nfse': '20/02/2026 15:17:37',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': {'texto': '-', 'totais_aproximados_tributos': '11,33% / 0,00% / 5,00%'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '39.549.075/0001-61',
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': '-',
               'inscricao_municipal': '163233',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '00000000000'},
 'servico': {'codigo_nbs': '109055000',
             'codigo_tributacao': '172001 - Consultoria e assessoria econômica ou financeira.',
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'descricao_tributacao': 'Consultoria e assessoria econômica ou financeira.',
             'local_prestacao': 'Arapiraca'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': 'ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '30210',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '46,40',
            'valor_liquido_nfse': '881,60',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '928,00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '928,00',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Arapiraca',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '46,40'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '928,00'},
 'watermark': ''})

def expected_nota_gov_215_1750331400100() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Prefeitura',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '21/05/2026',
                   'data_hora_emissao_dps': '21/05/2026 00:00:00',
                   'data_hora_emissao_nfse': '21/05/2026 15:25:44',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '215',
                   'numero_nfse': '215',
                   'qr_code_url': '',
                   'serie_dps': '100',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': {'texto': '-', 'totais_aproximados_tributos': '0,00 / 0,00 / 69,95'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '17.503.314/0001-00',
               'email': 's.aquino@hotmail.com',
               'endereco': '-',
               'inscricao_municipal': '402495',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': 'Regime de apuração dos tributos federais e municipal pelo SN',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Optante - Microempresa ou Empresa ...',
               'telefone': '82991048081'},
 'servico': {'codigo_nbs': '114011300',
             'codigo_tributacao': '170101 - Assessoria ou consultoria de qualquer natureza, não contida em outros '
                                  'itens desta lista.',
             'descricao_servico': 'CONTRATO 00358/26 AE 410162 ITEM 0001',
             'descricao_tributacao': 'Assessoria ou consultoria de qualquer natureza, não contida em outros itens '
                                     'desta lista.',
             'local_prestacao': 'DELMIRO GOUVEIA'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2702405 / 57.480-000',
             'documento': '12.517.413/0004-70',
             'email': 'andre.mauricio@al.sebrae.com.br',
             'endereco': 'Presidente Castelo Branco, nº 60, BLOCO F LOJA 01 ANEXO SHOPPING DA VILA -...',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '82991081790'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '69,95',
            'valor_liquido_nfse': '3.410,05',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '3.480,00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '2,01%',
                          'base_calculo_issqn': '-',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'DELMIRO GOUVEIA',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '69,95'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '3.480,00'},
 'watermark': ''})

def expected_nota_gov_2600000000196_17086031000100() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Prefeitura',
               'homologacao_aviso': '',
               'municipio_ambiente': 'PE',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '02/03/2026',
                   'data_hora_emissao_dps': '02/03/2026 13:27:57',
                   'data_hora_emissao_nfse': '02/03/2026 13:27:57',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '2600000000196',
                   'numero_nfse': '2600000000196',
                   'qr_code_url': '',
                   'serie_dps': '2026',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': None,
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '17.086.031/0001-00',
               'email': 'ATITUDESERVICOSEIRELI@GMAIL.COM',
               'endereco': '-',
               'inscricao_municipal': '0948411',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '81322843'},
 'servico': {'codigo_nbs': '118012100',
             'codigo_tributacao': '170501 - Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de '
                                  'empregados\n'
                                  '            ou trabalhadores, avulsos ou temporários, contratados pelo prestador de '
                                  'serviço.',
             'descricao_servico': 'PRESTACAO DE SERVICOS DE PORTARIA NO SEBRAE - SERVICO BRASILEIRO\n'
                                  '                            DE APOIO AS MICRO E PEQUENAS EMPRESAS EM ALAGOAS '
                                  'LOCALIZADO NA R 13 DE\n'
                                  '                            MAIO, N 310 - CENTRO, DELMIRO GOUVEIA - AL, CEP: '
                                  '57480-000. NO PERIODO\n'
                                  '                            DE JANEIRO DE 2026. AE: 409446 - ITENS: 0015 E 0017. '
                                  'DADOS BANCARIOS:\n'
                                  '                            BANCO: CAIXA ECONOMICA AGÊNCIA: 4253 CONTA CORRENTE: '
                                  '000577231652-0',
             'descricao_tributacao': 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de '
                                     'empregados\n'
                                     '            ou trabalhadores, avulsos ou temporários, contratados pelo prestador '
                                     'd...',
             'local_prestacao': 'DELMIRO GOUVEIA'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2702405 / 57.480-000',
             'documento': '12.517.413/0004-70',
             'email': '-',
             'endereco': 'R 13 DE MAIO, nº 310 - CENTRO',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS SEBRAE/AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '1.571,32',
            'valor_liquido_nfse': '11.559,99',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '14.754,28'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS Retidos',
                        'valor_cofins': '442,63',
                        'valor_pis': '95,90',
                        'valor_retencao_contribuicao_previdenciaria': '1.622,97',
                        'valor_retencao_csll': '147,54',
                        'valor_retencao_irrf': '147,54'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '14.754,28',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'DELMIRO GOUVEIA',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '737,71'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '14.754,28'},
 'watermark': ''})

def expected_nota_gov_2600000000197_17086031000100() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Prefeitura',
               'homologacao_aviso': '',
               'municipio_ambiente': 'PE',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '02/03/2026',
                   'data_hora_emissao_dps': '02/03/2026 13:31:55',
                   'data_hora_emissao_nfse': '02/03/2026 13:31:55',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '2600000000197',
                   'numero_nfse': '2600000000197',
                   'qr_code_url': '',
                   'serie_dps': '2026',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': None,
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '17.086.031/0001-00',
               'email': 'ATITUDESERVICOSEIRELI@GMAIL.COM',
               'endereco': '-',
               'inscricao_municipal': '0948411',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '81322843'},
 'servico': {'codigo_nbs': '118012100',
             'codigo_tributacao': '170501 - Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de '
                                  'empregados\n'
                                  '            ou trabalhadores, avulsos ou temporários, contratados pelo prestador de '
                                  'serviço.',
             'descricao_servico': 'PRESTACAO DE SERVICOS DE PORTARIA NO SEBRAE - SERVICO BRASILEIRO\n'
                                  '                            DE APOIO AS MICRO E PEQUENAS EMPRESAS EM ALAGOAS '
                                  'LOCALIZADO R ENGENHEIRO\n'
                                  '                            GORDILHO DE CASTRO, N 80 - CENTRO, ARAPIRACA - AL, CEP: '
                                  '57300-100. NO\n'
                                  '                            PERIODO DE JANEIRO DE 2026. AE: 409446 - ITENS: 0007 E '
                                  '0009. DADOS\n'
                                  '                            BANCARIOS: BANCO: CAIXA ECONOMICA AGÊNCIA: 4253 CONTA '
                                  'CORRENTE:\n'
                                  '                            000577231652-0',
             'descricao_tributacao': 'Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de '
                                     'empregados\n'
                                     '            ou trabalhadores, avulsos ou temporários, contratados pelo prestador '
                                     'd...',
             'local_prestacao': 'ARAPIRACA'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'nota.nfe@al.sebrae.com.br',
             'endereco': 'R ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS SEBRAE AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '1.573,36',
            'valor_liquido_nfse': '11.574,88',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '14.773,30'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS Retidos',
                        'valor_cofins': '443,20',
                        'valor_pis': '96,03',
                        'valor_retencao_contribuicao_previdenciaria': '1.625,06',
                        'valor_retencao_csll': '147,73',
                        'valor_retencao_irrf': '147,73'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '14.773,30',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'ARAPIRACA',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '738,67'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '14.773,30'},
 'watermark': ''})

def expected_nota_gov_2_39549075000161() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '02/03/2026',
                   'data_hora_emissao_dps': '02/03/2026 12:10:21',
                   'data_hora_emissao_nfse': '02/03/2026 12:10:21',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '2',
                   'numero_nfse': '2',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': {'texto': '-', 'totais_aproximados_tributos': '11,33% / 0,00% / 5,00%'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '39.549.075/0001-61',
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': '-',
               'inscricao_municipal': '163233',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '00000000000'},
 'servico': {'codigo_nbs': '109055000',
             'codigo_tributacao': '172001 - Consultoria e assessoria econômica ou financeira.',
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'descricao_tributacao': 'Consultoria e assessoria econômica ou financeira.',
             'local_prestacao': 'Arapiraca'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': 'ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '30210',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '69,60',
            'valor_liquido_nfse': '858,40',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '928,00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS/CSLL Retidos',
                        'valor_cofins': '27,84',
                        'valor_pis': '6,03',
                        'valor_retencao_contribuicao_previdenciaria': '-',
                        'valor_retencao_csll': '9,28',
                        'valor_retencao_irrf': '13,92'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '928,00',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Arapiraca',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '46,40'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '928,00'},
 'watermark': ''})

def expected_nota_gov_3_39549075000161() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '02/03/2026',
                   'data_hora_emissao_dps': '02/03/2026 16:46:04',
                   'data_hora_emissao_nfse': '02/03/2026 16:46:04',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '3',
                   'numero_nfse': '3',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e de Substituição Gerada'},
 'informacoes_complementares': {'texto': 'NFS-e substituída: 27003002239549075000161000000000000226030494932924',
                                'totais_aproximados_tributos': '11,33% / 0,00% / 5,00%'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '39.549.075/0001-61',
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': '-',
               'inscricao_municipal': '163233',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '00000000000'},
 'servico': {'codigo_nbs': '109055000',
             'codigo_tributacao': '172001 - Consultoria e assessoria econômica ou financeira.',
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'descricao_tributacao': 'Consultoria e assessoria econômica ou financeira.',
             'local_prestacao': 'Arapiraca'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': 'ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '30210',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '103,47',
            'valor_liquido_nfse': '824,53',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '928,00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS/CSLL Retidos',
                        'valor_cofins': '27,84',
                        'valor_pis': '6,03',
                        'valor_retencao_contribuicao_previdenciaria': '-',
                        'valor_retencao_csll': '43,15',
                        'valor_retencao_irrf': '13,92'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '928,00',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Arapiraca',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '46,40'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '928,00'},
 'watermark': ''})

def expected_nota_gov_439_01107244000130() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'BA',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '09/02/2026',
                   'data_hora_emissao_dps': '09/02/2026 16:55:52',
                   'data_hora_emissao_nfse': '09/02/2026 16:55:52',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '2',
                   'numero_nfse': '439',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': '107'},
 'informacoes_complementares': None,
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '01.107.244/0001-30',
               'email': 'reidaschaves.carimbos@gmail.com',
               'endereco': '-',
               'inscricao_municipal': '-',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Optante - Microempreendedor Indivi...',
               'telefone': '75988589950'},
 'servico': {'codigo_nbs': '-',
             'codigo_tributacao': '240101 - Serviços de chaveiros, confecção de carimbos e congêneres.',
             'descricao_servico': '01 CÓPIA DE CHAVE YALE',
             'descricao_tributacao': 'Serviços de chaveiros, confecção de carimbos e congêneres.',
             'local_prestacao': 'Paulo Afonso'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2702405 / 57.480-000',
             'documento': '12.517.413/0004-70',
             'email': '-',
             'endereco': 'PRESIDENTE CASTELO BRANCO, nº 60, BLOCO F LOJA 01 ANEXO SHOPPING DA VILA -...',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '-',
            'valor_liquido_nfse': '13,00',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '13,00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '-',
                          'base_calculo_issqn': '-',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Paulo Afonso',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Não Retido',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '-'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '13,00'},
 'watermark': ''})

def expected_nota_gov_4578_16819228000148() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Prefeitura',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '03/03/2026',
                   'data_hora_emissao_dps': '03/03/2026 11:16:30',
                   'data_hora_emissao_nfse': '03/03/2026 11:16:30',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '4578',
                   'numero_nfse': '4578',
                   'qr_code_url': '',
                   'serie_dps': '10000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': {'texto': '-', 'totais_aproximados_tributos': '0,00 / 0,00 / 0,00'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '16.819.228/0001-48',
               'email': '-',
               'endereco': '-',
               'inscricao_municipal': '901186694',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '-'},
 'servico': {'codigo_nbs': '-',
             'codigo_tributacao': '171001 - Planejamento, Organização E Administração De Feiras, Exposições, E '
                                  'Congêneres. / 001',
             'descricao_servico': 'serviços de organização de feiras, congressos, exposições e\n'
                                  '                            festas',
             'descricao_tributacao': 'Planejamento, Organização E Administração De Feiras, Exposições, E Congêneres.',
             'local_prestacao': 'MACEIÃ¿'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2702405 / 57.480-000',
             'documento': '12.517.413/0004-70',
             'email': '-',
             'endereco': 'Rua TODOS, nº 310 - Delmiro Gouveia',
             'inscricao_municipal': '-',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS - SEBRAE AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '57,91',
            'valor_liquido_nfse': '901,62',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '1.158,15'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS Retidos',
                        'valor_cofins': '34,74',
                        'valor_pis': '7,53',
                        'valor_retencao_contribuicao_previdenciaria': '127,40',
                        'valor_retencao_csll': '11,58',
                        'valor_retencao_irrf': '17,37'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '1.158,15',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'DELMIRO GOUVEIA',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '57,91'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '1.158,15'},
 'watermark': ''})

def expected_nota_gov_4_39549075000161() -> FormattedDanfse:
    return FormattedDanfse.model_validate({'cabecalho': {'ambiente_gerador': 'Sistema Nacional da NFS-e',
               'homologacao_aviso': '',
               'municipio_ambiente': 'AL',
               'tipo_ambiente': 'Produção'},
 'canhoto': None,
 'destinatario': {'bloco_texto': 'Destinatário da operação não identificado na NFS-e',
                  'codigo_ibge_cep': '-',
                  'documento': '-',
                  'email': '-',
                  'endereco': '-',
                  'inscricao_municipal': '-',
                  'municipio_uf': '-',
                  'nome': '-',
                  'telefone': '-'},
 'identificacao': {'chave_acesso': '-',
                   'competencia_nfse': '09/03/2026',
                   'data_hora_emissao_dps': '09/03/2026 12:40:20',
                   'data_hora_emissao_nfse': '09/03/2026 12:40:20',
                   'emitente_nfse': 'Prestador',
                   'finalidade_nfse': '-',
                   'numero_dps': '4',
                   'numero_nfse': '4',
                   'qr_code_url': '',
                   'serie_dps': '70000',
                   'situacao_nfse': 'NFS-e Gerada'},
 'informacoes_complementares': {'texto': '-', 'totais_aproximados_tributos': '11,33% / 0,00% / 5,00%'},
 'intermediario': {'bloco_texto': 'Intermediário do Serviço não identificado na NFS-e',
                   'codigo_ibge_cep': '-',
                   'documento': '-',
                   'email': '-',
                   'endereco': '-',
                   'inscricao_municipal': '-',
                   'municipio_uf': '-',
                   'nome': '-',
                   'telefone': '-'},
 'prestador': {'codigo_ibge_cep': '-',
               'documento': '39.549.075/0001-61',
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': '-',
               'inscricao_municipal': '163233',
               'municipio_uf': '-',
               'nome': '-',
               'regime_apuracao_tributaria_sn': '-',
               'regime_especial_tributacao': 'Nenhum',
               'simples_nacional_competencia': 'Não Optante',
               'telefone': '00000000000'},
 'servico': {'codigo_nbs': '114011200',
             'codigo_tributacao': '172001 - Consultoria e assessoria econômica ou financeira.',
             'descricao_servico': 'Contrato 00189/26 AE 409212 Item 0001',
             'descricao_tributacao': 'Consultoria e assessoria econômica ou financeira.',
             'local_prestacao': 'Arapiraca'},
 'tomador': {'bloco_texto': '',
             'codigo_ibge_cep': '2700300 / 57.300-100',
             'documento': '12.517.413/0002-08',
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': 'ENGENHEIRO GORDILHO DE CASTRO, nº 80 - CENTRO',
             'inscricao_municipal': '30210',
             'municipio_uf': '-',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '-'},
 'totais': {'desconto_condicionado': '-',
            'desconto_incondicionado': '-',
            'total_ibs_cbs': '-',
            'total_retencoes': '129,34',
            'valor_liquido_nfse': '1.030,66',
            'valor_liquido_nfse_mais_ibs_cbs': '-',
            'valor_operacao_servico': '1.160,00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': 'PIS/COFINS/CSLL Retidos',
                        'valor_cofins': '34,80',
                        'valor_pis': '7,54',
                        'valor_retencao_contribuicao_previdenciaria': '-',
                        'valor_retencao_csll': '53,94',
                        'valor_retencao_irrf': '17,40'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5,00%',
                          'base_calculo_issqn': '1.160,00',
                          'beneficio_municipal': '-',
                          'bloco_texto': '',
                          'calculo_beneficio_municipal': '-',
                          'desconto_incondicionado': '-',
                          'local_incidencia': 'Arapiraca',
                          'numero_processo_suspensao': '-',
                          'regime_especial_tributacao_issqn': 'Nenhum',
                          'retencao_issqn': 'Retido pelo Tomador',
                          'suspensao_exigibilidade': '-',
                          'tipo_imunidade_issqn': '-',
                          'tipo_tributacao_issqn': 'Operação tributável',
                          'total_deducoes_reducoes': '-',
                          'valor_issqn_apurado': '58,00'},
 'valores_servico': {'desconto_condicionado': '-', 'desconto_incondicionado': '-', 'valor_servico': '1.160,00'},
 'watermark': ''})

EXPECTED_FORMATTED_BY_FIXTURE = {
    "tests/fixtures/gov/nota_gov_1_29154166000144.xml": expected_nota_gov_1_29154166000144(),
    "tests/fixtures/gov/nota_gov_1_33762922000195.xml": expected_nota_gov_1_33762922000195(),
    "tests/fixtures/gov/nota_gov_1_39549075000161.xml": expected_nota_gov_1_39549075000161(),
    "tests/fixtures/gov/nota_gov_215_1750331400100.xml": expected_nota_gov_215_1750331400100(),
    "tests/fixtures/gov/nota_gov_2600000000196_17086031000100.xml": expected_nota_gov_2600000000196_17086031000100(),
    "tests/fixtures/gov/nota_gov_2600000000197_17086031000100.xml": expected_nota_gov_2600000000197_17086031000100(),
    "tests/fixtures/gov/nota_gov_2_39549075000161.xml": expected_nota_gov_2_39549075000161(),
    "tests/fixtures/gov/nota_gov_3_39549075000161.xml": expected_nota_gov_3_39549075000161(),
    "tests/fixtures/gov/nota_gov_439_01107244000130.xml": expected_nota_gov_439_01107244000130(),
    "tests/fixtures/gov/nota_gov_4578_16819228000148.xml": expected_nota_gov_4578_16819228000148(),
    "tests/fixtures/gov/nota_gov_4_39549075000161.xml": expected_nota_gov_4_39549075000161(),
}
