from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from danfse.domain.models import (
    BeneficioMunicipalDanfse,
    CabecalhoDanfse,
    CanhotoDanfse,
    CbsDanfse,
    ClassificacaoTributariaIbsCbsDanfse,
    CodigoServicoDanfse,
    DanfseData,
    DeducoesReducoesDanfse,
    DestinatarioDanfse,
    DocumentoPessoaDanfse,
    EnderecoDanfse,
    EventoDanfse,
    ExclusoesReducoesBaseCalculoIbsCbsDanfse,
    IbsMunicipalDanfse,
    IbsUfDanfse,
    ImovelDanfse,
    IncidenciaIbsCbsDanfse,
    InformacoesComplementaresDanfse,
    IdentificacaoNfseDanfse,
    IntermediarioDanfse,
    LocalIncidenciaIssqnDanfse,
    LocalPrestacaoDanfse,
    ObraDanfse,
    PedidoDanfse,
    PrestadorDanfse,
    RegimeTributarioPrestadorDanfse,
    ServicoPrestadoDanfse,
    StatusVisualDanfse,
    SuspensaoExigibilidadeIssqnDanfse,
    TomadorDanfse,
    TotaisAproximadosTributosDanfse,
    TotaisDanfse,
    TributacaoFederalDanfse,
    TributacaoIbsCbsDanfse,
    TributacaoMunicipalDanfse,
    ValoresServicoDanfse,
)
def expected_nota_gov_1_29154166000144() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2', 'municipio_emitente': 'Arapiraca', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27003002229154166000144000000000000126021697058440',
                   'competencia_nfse': '2026-02-23',
                   'data_hora_emissao_dps': '2026-02-23T16:51:42-03:00',
                   'data_hora_emissao_nfse': '2026-02-23T16:51:42-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'serie_dps': '70000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': None,
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '29154166000144', 'cpf': None, 'nif': None},
               'email': 'cccpfiscal@hotmail.com',
               'endereco': {'bairro': 'SÃO LUIZ',
                            'cep': '57301280',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2700300',
                            'complemento': None,
                            'logradouro': 'RUA ODILON ARAÚJO AMORIM',
                            'municipio': 'Arapiraca',
                            'numero': '268',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '152794',
               'nome': 'ELO3 ARQUITETURA LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': '1',
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '3'},
               'telefone': '8235213576'},
 'servico': {'codigo_servico': {'codigo_nbs': '114021100',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '170101',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Assessoria ou consultoria de qualquer natureza, não '
                                                                 'contida em outros itens desta\n'
                                                                 '            lista.'},
             'descricao_servico': '00103/26 AE 409051 Item 0001',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Arapiraca',
                                 'municipio': 'Arapiraca',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': '30210',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '20.10',
            'valor_liquido_nfse': '979.90',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '1000.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': None,
                        'valor_cofins_debito_apuracao_propria': None,
                        'valor_pis_debito_apuracao_propria': None,
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': None,
                        'valor_retencao_irrf': None},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '2.01',
                          'base_calculo_issqn': '1000.00',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Arapiraca',
                                               'municipio': 'Arapiraca',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '20.10'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '1000.00'}})

def expected_nota_gov_1_33762922000195() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2',
               'municipio_emitente': 'Pão de Açúcar',
               'tipo_ambiente': '1',
               'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27064062233762922000195000000000000126035379315790',
                   'competencia_nfse': '2026-03-12',
                   'data_hora_emissao_dps': '2026-03-12T16:35:01-03:00',
                   'data_hora_emissao_nfse': '2026-03-12T16:35:01-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'serie_dps': '70000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': None,
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '33762922000195', 'cpf': None, 'nif': None},
               'email': 'CARVALHOCONTABILIDADE001@GMAIL.COM',
               'endereco': {'bairro': 'CENTRO',
                            'cep': '57400000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2706406',
                            'complemento': None,
                            'logradouro': 'FERREIRA DE NOVAES',
                            'municipio': 'Pão de Açúcar',
                            'numero': 'SN',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': None,
               'nome': 'JANAYNA SOARES RIBEIRO',
               'regime_tributario': {'regime_apuracao_tributaria_sn': '1',
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '3'},
               'telefone': '8299301159'},
 'servico': {'codigo_servico': {'codigo_nbs': None,
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '171101',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Organização de festas e recepções.'},
             'descricao_servico': 'Serviço e Fornecimento de Alimentação, Almoço!',
             'local_prestacao': {'codigo_municipio': '2706406',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Pão de Açúcar',
                                 'municipio': 'Pão de Açúcar',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000470', 'cpf': None, 'nif': None},
             'email': None,
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57480000',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2702405',
                          'complemento': 'BLOCO F LOJA 01 ANEXO SHOPPING DA VILA',
                          'logradouro': 'PRESIDENTE CASTELO BRANCO',
                          'municipio': None,
                          'numero': '60',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': None,
            'valor_liquido_nfse': '43.00',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '43.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': None,
                        'valor_cofins_debito_apuracao_propria': None,
                        'valor_pis_debito_apuracao_propria': None,
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': None,
                        'valor_retencao_irrf': None},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': None,
                          'base_calculo_issqn': None,
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Pão de Açúcar',
                                               'municipio': 'Pão de Açúcar',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '1',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': None},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '43.00'}})

def expected_nota_gov_1_39549075000161() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2', 'municipio_emitente': 'Arapiraca', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27003002239549075000161000000000000126022815870141',
                   'competencia_nfse': '2026-02-20',
                   'data_hora_emissao_dps': '2026-02-20T15:17:37-03:00',
                   'data_hora_emissao_nfse': '2026-02-20T15:17:37-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '1',
                   'numero_nfse': '1',
                   'serie_dps': '70000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': {'chave_nfse_substituida': None,
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': '0.00',
                                                                'percentual_total_tributos_federais': '11.33',
                                                                'percentual_total_tributos_municipais': '5.00',
                                                                'valor_total_tributos_estaduais': None,
                                                                'valor_total_tributos_federais': None,
                                                                'valor_total_tributos_municipais': None}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '39549075000161', 'cpf': None, 'nif': None},
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': {'bairro': 'ELDORADO',
                            'cep': '57306000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2700300',
                            'complemento': 'SALA 21',
                            'logradouro': 'RUA EXPEDICIONÁRIOS BRASILEIROS',
                            'municipio': 'Arapiraca',
                            'numero': '600',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '163233',
               'nome': 'INSTITUTO JULIAN LEMOS DE DESENVOLVIMENTO FINANCEIRO LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '00000000000'},
 'servico': {'codigo_servico': {'codigo_nbs': '109055000',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '172001',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Consultoria e assessoria econômica ou financeira.'},
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Arapiraca',
                                 'municipio': 'Arapiraca',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': '30210',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '46.40',
            'valor_liquido_nfse': '881.60',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '928.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': None,
                        'valor_cofins_debito_apuracao_propria': None,
                        'valor_pis_debito_apuracao_propria': None,
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': None,
                        'valor_retencao_irrf': None},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '928.00',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Arapiraca',
                                               'municipio': 'Arapiraca',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '46.40'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '928.00'}})

def expected_nota_gov_215_1750331400100() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '1',
               'municipio_emitente': 'DELMIRO GOUVEIA',
               'tipo_ambiente': '1',
               'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27024051217503314000100000000000021526050005479233',
                   'competencia_nfse': '2026-05-21',
                   'data_hora_emissao_dps': '2026-05-21T00:00:00-03:00',
                   'data_hora_emissao_nfse': '2026-05-21T15:25:44-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '215',
                   'numero_nfse': '215',
                   'serie_dps': '100',
                   'situacao_nfse': '100'},
 'informacoes_complementares': {'chave_nfse_substituida': None,
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': None,
                                                                'percentual_total_tributos_federais': None,
                                                                'percentual_total_tributos_municipais': None,
                                                                'valor_total_tributos_estaduais': '0',
                                                                'valor_total_tributos_federais': '0.00',
                                                                'valor_total_tributos_municipais': '69.95'}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '17503314000100', 'cpf': None, 'nif': None},
               'email': 's.aquino@hotmail.com',
               'endereco': {'bairro': 'Centro',
                            'cep': '57480000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2702405',
                            'complemento': None,
                            'logradouro': 'Angelita Oliveira de Souza',
                            'municipio': 'DELMIRO GOUVEIA',
                            'numero': '123',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '402495',
               'nome': 'CREARE CONSULTORIA E ASSESSORIA EMPRESARIAL E PESSOAL S/S',
               'regime_tributario': {'regime_apuracao_tributaria_sn': '1',
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '3'},
               'telefone': '82991048081'},
 'servico': {'codigo_servico': {'codigo_nbs': '114011300',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '170101',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Assessoria ou consultoria de qualquer natureza, não '
                                                                 'contida em outros itens desta lista.'},
             'descricao_servico': 'CONTRATO 00358/26 AE 410162 ITEM 0001',
             'local_prestacao': {'codigo_municipio': '2702405',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'DELMIRO GOUVEIA',
                                 'municipio': 'DELMIRO GOUVEIA',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000470', 'cpf': None, 'nif': None},
             'email': 'andre.mauricio@al.sebrae.com.br',
             'endereco': {'bairro': 'Centro',
                          'cep': '57480000',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2702405',
                          'complemento': 'BLOCO F LOJA 01 ANEXO SHOPPING DA VILA',
                          'logradouro': 'Presidente Castelo Branco',
                          'municipio': None,
                          'numero': '60',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': '82991081790'},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '69.95',
            'valor_liquido_nfse': '3410.05',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '3480.00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '2.01',
                          'base_calculo_issqn': None,
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'DELMIRO GOUVEIA',
                                               'municipio': 'DELMIRO GOUVEIA',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '69.95'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '3480.00'}})

def expected_nota_gov_2600000000196_17086031000100() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '1', 'municipio_emitente': 'OLINDA', 'tipo_ambiente': '1', 'uf_emitente': 'PE'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '26096001217086031000100260000000019626034839361533',
                   'competencia_nfse': '2026-03-02',
                   'data_hora_emissao_dps': '2026-03-02T13:27:57Z',
                   'data_hora_emissao_nfse': '2026-03-02T13:27:57Z',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '2600000000196',
                   'numero_nfse': '2600000000196',
                   'serie_dps': '2026',
                   'situacao_nfse': '100'},
 'informacoes_complementares': None,
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '17086031000100', 'cpf': None, 'nif': None},
               'email': 'ATITUDESERVICOSEIRELI@GMAIL.COM',
               'endereco': {'bairro': 'CASA CAIADA',
                            'cep': '53130550',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2609600',
                            'complemento': None,
                            'logradouro': 'RUA DR EPAMINONDAS DE MELO',
                            'municipio': 'OLINDA',
                            'numero': '67',
                            'pais': None,
                            'uf': 'PE'},
               'inscricao_municipal': '0948411',
               'nome': 'ATITUDE SERVICOS DE LIMPEZA LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '81322843'},
 'servico': {'codigo_servico': {'codigo_nbs': '118012100',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '170501',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Fornecimento de mão-de-obra, mesmo em caráter '
                                                                 'temporário, inclusive de empregados\n'
                                                                 '            ou trabalhadores, avulsos ou '
                                                                 'temporários, contratados pelo prestador de serviço.'},
             'descricao_servico': 'PRESTACAO DE SERVICOS DE PORTARIA NO SEBRAE - SERVICO BRASILEIRO\n'
                                  '                            DE APOIO AS MICRO E PEQUENAS EMPRESAS EM ALAGOAS '
                                  'LOCALIZADO NA R 13 DE\n'
                                  '                            MAIO, N 310 - CENTRO, DELMIRO GOUVEIA - AL, CEP: '
                                  '57480-000. NO PERIODO\n'
                                  '                            DE JANEIRO DE 2026. AE: 409446 - ITENS: 0015 E 0017. '
                                  'DADOS BANCARIOS:\n'
                                  '                            BANCO: CAIXA ECONOMICA AGÊNCIA: 4253 CONTA CORRENTE: '
                                  '000577231652-0',
             'local_prestacao': {'codigo_municipio': '2702405',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'DELMIRO GOUVEIA',
                                 'municipio': 'DELMIRO GOUVEIA',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000470', 'cpf': None, 'nif': None},
             'email': None,
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57480000',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2702405',
                          'complemento': None,
                          'logradouro': 'R 13 DE MAIO',
                          'municipio': None,
                          'numero': '310',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS SEBRAE/AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '1571.32',
            'valor_liquido_nfse': '11559.99',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '14754.28'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '1',
                        'valor_cofins_debito_apuracao_propria': '442.63',
                        'valor_pis_debito_apuracao_propria': '95.90',
                        'valor_retencao_contribuicao_previdenciaria': '1622.97',
                        'valor_retencao_csll': '147.54',
                        'valor_retencao_irrf': '147.54'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '14754.28',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'DELMIRO GOUVEIA',
                                               'municipio': 'DELMIRO GOUVEIA',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '737.71'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '14754.28'}})

def expected_nota_gov_2600000000197_17086031000100() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '1', 'municipio_emitente': 'OLINDA', 'tipo_ambiente': '1', 'uf_emitente': 'PE'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '26096001217086031000100260000000019726030868526317',
                   'competencia_nfse': '2026-03-02',
                   'data_hora_emissao_dps': '2026-03-02T13:31:55Z',
                   'data_hora_emissao_nfse': '2026-03-02T13:31:55Z',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '2600000000197',
                   'numero_nfse': '2600000000197',
                   'serie_dps': '2026',
                   'situacao_nfse': '100'},
 'informacoes_complementares': None,
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '17086031000100', 'cpf': None, 'nif': None},
               'email': 'ATITUDESERVICOSEIRELI@GMAIL.COM',
               'endereco': {'bairro': 'CASA CAIADA',
                            'cep': '53130550',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2609600',
                            'complemento': None,
                            'logradouro': 'RUA DR EPAMINONDAS DE MELO',
                            'municipio': 'OLINDA',
                            'numero': '67',
                            'pais': None,
                            'uf': 'PE'},
               'inscricao_municipal': '0948411',
               'nome': 'ATITUDE SERVICOS DE LIMPEZA LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '81322843'},
 'servico': {'codigo_servico': {'codigo_nbs': '118012100',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '170501',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Fornecimento de mão-de-obra, mesmo em caráter '
                                                                 'temporário, inclusive de empregados\n'
                                                                 '            ou trabalhadores, avulsos ou '
                                                                 'temporários, contratados pelo prestador de serviço.'},
             'descricao_servico': 'PRESTACAO DE SERVICOS DE PORTARIA NO SEBRAE - SERVICO BRASILEIRO\n'
                                  '                            DE APOIO AS MICRO E PEQUENAS EMPRESAS EM ALAGOAS '
                                  'LOCALIZADO R ENGENHEIRO\n'
                                  '                            GORDILHO DE CASTRO, N 80 - CENTRO, ARAPIRACA - AL, CEP: '
                                  '57300-100. NO\n'
                                  '                            PERIODO DE JANEIRO DE 2026. AE: 409446 - ITENS: 0007 E '
                                  '0009. DADOS\n'
                                  '                            BANCARIOS: BANCO: CAIXA ECONOMICA AGÊNCIA: 4253 CONTA '
                                  'CORRENTE:\n'
                                  '                            000577231652-0',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'ARAPIRACA',
                                 'municipio': 'ARAPIRACA',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'nota.nfe@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'R ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS SEBRAE AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '1573.36',
            'valor_liquido_nfse': '11574.88',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '14773.30'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '1',
                        'valor_cofins_debito_apuracao_propria': '443.20',
                        'valor_pis_debito_apuracao_propria': '96.03',
                        'valor_retencao_contribuicao_previdenciaria': '1625.06',
                        'valor_retencao_csll': '147.73',
                        'valor_retencao_irrf': '147.73'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '14773.30',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'ARAPIRACA',
                                               'municipio': 'ARAPIRACA',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '738.67'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '14773.30'}})

def expected_nota_gov_2_39549075000161() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2', 'municipio_emitente': 'Arapiraca', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27003002239549075000161000000000000226030494932924',
                   'competencia_nfse': '2026-03-02',
                   'data_hora_emissao_dps': '2026-03-02T12:10:21-03:00',
                   'data_hora_emissao_nfse': '2026-03-02T12:10:21-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '2',
                   'numero_nfse': '2',
                   'serie_dps': '70000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': {'chave_nfse_substituida': None,
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': '0.00',
                                                                'percentual_total_tributos_federais': '11.33',
                                                                'percentual_total_tributos_municipais': '5.00',
                                                                'valor_total_tributos_estaduais': None,
                                                                'valor_total_tributos_federais': None,
                                                                'valor_total_tributos_municipais': None}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '39549075000161', 'cpf': None, 'nif': None},
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': {'bairro': 'ELDORADO',
                            'cep': '57306000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2700300',
                            'complemento': 'SALA 21',
                            'logradouro': 'RUA EXPEDICIONÁRIOS BRASILEIROS',
                            'municipio': 'Arapiraca',
                            'numero': '600',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '163233',
               'nome': 'INSTITUTO JULIAN LEMOS DE DESENVOLVIMENTO FINANCEIRO LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '00000000000'},
 'servico': {'codigo_servico': {'codigo_nbs': '109055000',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '172001',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Consultoria e assessoria econômica ou financeira.'},
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Arapiraca',
                                 'municipio': 'Arapiraca',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': '30210',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '69.60',
            'valor_liquido_nfse': '858.40',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '928.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '3',
                        'valor_cofins_debito_apuracao_propria': '27.84',
                        'valor_pis_debito_apuracao_propria': '6.03',
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': '9.28',
                        'valor_retencao_irrf': '13.92'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '928.00',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Arapiraca',
                                               'municipio': 'Arapiraca',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '46.40'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '928.00'}})

def expected_nota_gov_3_39549075000161() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2', 'municipio_emitente': 'Arapiraca', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27003002239549075000161000000000000326032200456003',
                   'competencia_nfse': '2026-03-02',
                   'data_hora_emissao_dps': '2026-03-02T16:46:04-03:00',
                   'data_hora_emissao_nfse': '2026-03-02T16:46:04-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '3',
                   'numero_nfse': '3',
                   'serie_dps': '70000',
                   'situacao_nfse': '101'},
 'informacoes_complementares': {'chave_nfse_substituida': '27003002239549075000161000000000000226030494932924',
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': '0.00',
                                                                'percentual_total_tributos_federais': '11.33',
                                                                'percentual_total_tributos_municipais': '5.00',
                                                                'valor_total_tributos_estaduais': None,
                                                                'valor_total_tributos_federais': None,
                                                                'valor_total_tributos_municipais': None}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '39549075000161', 'cpf': None, 'nif': None},
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': {'bairro': 'ELDORADO',
                            'cep': '57306000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2700300',
                            'complemento': 'SALA 21',
                            'logradouro': 'RUA EXPEDICIONÁRIOS BRASILEIROS',
                            'municipio': 'Arapiraca',
                            'numero': '600',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '163233',
               'nome': 'INSTITUTO JULIAN LEMOS DE DESENVOLVIMENTO FINANCEIRO LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '00000000000'},
 'servico': {'codigo_servico': {'codigo_nbs': '109055000',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '172001',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Consultoria e assessoria econômica ou financeira.'},
             'descricao_servico': 'Contrato 00146/26 AE 409112 Item 0001',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Arapiraca',
                                 'municipio': 'Arapiraca',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': '30210',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '103.47',
            'valor_liquido_nfse': '824.53',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '928.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '3',
                        'valor_cofins_debito_apuracao_propria': '27.84',
                        'valor_pis_debito_apuracao_propria': '6.03',
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': '43.15',
                        'valor_retencao_irrf': '13.92'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '928.00',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Arapiraca',
                                               'municipio': 'Arapiraca',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '46.40'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '928.00'}})

def expected_nota_gov_439_01107244000130() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2',
               'municipio_emitente': 'Paulo Afonso',
               'tipo_ambiente': '1',
               'uf_emitente': 'BA'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '29240092201107244000130000000000043926021649816521',
                   'competencia_nfse': '2026-02-09',
                   'data_hora_emissao_dps': '2026-02-09T16:55:52-03:00',
                   'data_hora_emissao_nfse': '2026-02-09T16:55:52-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '2',
                   'numero_nfse': '439',
                   'serie_dps': '70000',
                   'situacao_nfse': '107'},
 'informacoes_complementares': None,
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '01107244000130', 'cpf': None, 'nif': None},
               'email': 'reidaschaves.carimbos@gmail.com',
               'endereco': {'bairro': 'CENTRO',
                            'cep': '48602005',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2924009',
                            'complemento': None,
                            'logradouro': 'AV OTAVIANO LEANDRO DE MORAES',
                            'municipio': 'Paulo Afonso',
                            'numero': '133',
                            'pais': None,
                            'uf': 'BA'},
               'inscricao_municipal': None,
               'nome': 'JAQUES FONTES MELO',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '2'},
               'telefone': '75988589950'},
 'servico': {'codigo_servico': {'codigo_nbs': None,
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '240101',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Serviços de chaveiros, confecção de carimbos e '
                                                                 'congêneres.'},
             'descricao_servico': '01 CÓPIA DE CHAVE YALE',
             'local_prestacao': {'codigo_municipio': '2924009',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Paulo Afonso',
                                 'municipio': 'Paulo Afonso',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000470', 'cpf': None, 'nif': None},
             'email': None,
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57480000',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2702405',
                          'complemento': 'BLOCO F LOJA 01 ANEXO SHOPPING DA VILA',
                          'logradouro': 'PRESIDENTE CASTELO BRANCO',
                          'municipio': None,
                          'numero': '60',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': None,
            'valor_liquido_nfse': '13.00',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '13.00'},
 'tributacao_federal': None,
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': None,
                          'base_calculo_issqn': None,
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Paulo Afonso',
                                               'municipio': 'Paulo Afonso',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '1',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': None},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '13.00'}})

def expected_nota_gov_4578_16819228000148() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '1', 'municipio_emitente': 'MACEIÓ', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27043021216819228000148000000000457826030000000009',
                   'competencia_nfse': '2026-03-03',
                   'data_hora_emissao_dps': '2026-03-03T11:16:30-03:00',
                   'data_hora_emissao_nfse': '2026-03-03T11:16:30-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '4578',
                   'numero_nfse': '4578',
                   'serie_dps': '10000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': {'chave_nfse_substituida': None,
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': None,
                                                                'percentual_total_tributos_federais': None,
                                                                'percentual_total_tributos_municipais': None,
                                                                'valor_total_tributos_estaduais': '0.00',
                                                                'valor_total_tributos_federais': '0.00',
                                                                'valor_total_tributos_municipais': '0.00'}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '16819228000148', 'cpf': None, 'nif': None},
               'email': None,
               'endereco': {'bairro': 'Poço',
                            'cep': '57025000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2704302',
                            'complemento': 'PRÓXIMO AO MOINHO',
                            'logradouro': 'Comendador Leão',
                            'municipio': 'MACEIÓ',
                            'numero': '958',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '901186694',
               'nome': 'MANDALA PROMOCAO E MARKETING LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '30271010'},
 'servico': {'codigo_servico': {'codigo_nbs': None,
                                'codigo_tributacao_municipal': '001',
                                'codigo_tributacao_nacional': '171001',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Planejamento, Organização E Administração De Feiras, '
                                                                 'Exposições, E Congêneres.'},
             'descricao_servico': 'serviços de organização de feiras, congressos, exposições e\n'
                                  '                            festas',
             'local_prestacao': {'codigo_municipio': '2702405',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'MACEIÃ¿',
                                 'municipio': 'MACEIÃ¿',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000470', 'cpf': None, 'nif': None},
             'email': None,
             'endereco': {'bairro': 'Delmiro Gouveia',
                          'cep': '57480000',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2702405',
                          'complemento': None,
                          'logradouro': 'Rua TODOS',
                          'municipio': None,
                          'numero': '310',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': None,
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS - SEBRAE AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '57.91',
            'valor_liquido_nfse': '901.62',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '1158.15'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '1',
                        'valor_cofins_debito_apuracao_propria': '34.74',
                        'valor_pis_debito_apuracao_propria': '7.53',
                        'valor_retencao_contribuicao_previdenciaria': '127.40',
                        'valor_retencao_csll': '11.58',
                        'valor_retencao_irrf': '17.37'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '1158.15',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'DELMIRO GOUVEIA',
                                               'municipio': 'DELMIRO GOUVEIA',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '57.91'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '1158.15'}})

def expected_nota_gov_4_39549075000161() -> DanfseData:
    return DanfseData.model_validate({'cabecalho': {'ambiente_gerador': '2', 'municipio_emitente': 'Arapiraca', 'tipo_ambiente': '1', 'uf_emitente': 'AL'},
 'canhoto': None,
 'destinatario': None,
 'identificacao': {'chave_acesso': '27003002239549075000161000000000000426039357825434',
                   'competencia_nfse': '2026-03-09',
                   'data_hora_emissao_dps': '2026-03-09T12:40:20-03:00',
                   'data_hora_emissao_nfse': '2026-03-09T12:40:20-03:00',
                   'emitente_nfse': '1',
                   'finalidade_nfse': None,
                   'numero_dps': '4',
                   'numero_nfse': '4',
                   'serie_dps': '70000',
                   'situacao_nfse': '100'},
 'informacoes_complementares': {'chave_nfse_substituida': None,
                                'documento_referenciado': None,
                                'documento_tecnico': None,
                                'evento': None,
                                'imovel': None,
                                'informacoes_administracao_tributaria_municipal': None,
                                'informacoes_complementares': None,
                                'obra': None,
                                'outras_informacoes': None,
                                'pedido': None,
                                'totais_aproximados_tributos': {'percentual_total_tributos_estaduais': '0.00',
                                                                'percentual_total_tributos_federais': '11.33',
                                                                'percentual_total_tributos_municipais': '5.00',
                                                                'valor_total_tributos_estaduais': None,
                                                                'valor_total_tributos_federais': None,
                                                                'valor_total_tributos_municipais': None}},
 'intermediario': None,
 'prestador': {'documento': {'cnpj': '39549075000161', 'cpf': None, 'nif': None},
               'email': 'julianlemos.financeiro@gmail.com',
               'endereco': {'bairro': 'ELDORADO',
                            'cep': '57306000',
                            'codigo_enderecamento_postal_exterior': None,
                            'codigo_municipio': '2700300',
                            'complemento': 'SALA 21',
                            'logradouro': 'RUA EXPEDICIONÁRIOS BRASILEIROS',
                            'municipio': 'Arapiraca',
                            'numero': '600',
                            'pais': None,
                            'uf': 'AL'},
               'inscricao_municipal': '163233',
               'nome': 'INSTITUTO JULIAN LEMOS DE DESENVOLVIMENTO FINANCEIRO LTDA',
               'regime_tributario': {'regime_apuracao_tributaria_sn': None,
                                     'regime_especial_tributacao': '0',
                                     'simples_nacional_competencia': '1'},
               'telefone': '00000000000'},
 'servico': {'codigo_servico': {'codigo_nbs': '114011200',
                                'codigo_tributacao_municipal': None,
                                'codigo_tributacao_nacional': '172001',
                                'descricao_tributacao_municipal': None,
                                'descricao_tributacao_nacional': 'Consultoria e assessoria econômica ou financeira.'},
             'descricao_servico': 'Contrato 00189/26 AE 409212 Item 0001',
             'local_prestacao': {'codigo_municipio': '2700300',
                                 'codigo_pais_prestacao': None,
                                 'local_prestacao_texto': 'Arapiraca',
                                 'municipio': 'Arapiraca',
                                 'pais': None,
                                 'uf': None}},
 'status_visual': {'destinatario_igual_tomador': False,
                   'destinatario_nao_identificado': True,
                   'intermediario_nao_identificado': True,
                   'is_cancelada': False,
                   'is_homologacao': False,
                   'is_substituida': False,
                   'operacao_nao_sujeita_issqn': False,
                   'tomador_nao_identificado': False},
 'tomador': {'documento': {'cnpj': '12517413000208', 'cpf': None, 'nif': None},
             'email': 'verdiana.lopes@al.sebrae.com.br',
             'endereco': {'bairro': 'CENTRO',
                          'cep': '57300100',
                          'codigo_enderecamento_postal_exterior': None,
                          'codigo_municipio': '2700300',
                          'complemento': None,
                          'logradouro': 'ENGENHEIRO GORDILHO DE CASTRO',
                          'municipio': None,
                          'numero': '80',
                          'pais': None,
                          'uf': None},
             'inscricao_municipal': '30210',
             'nome': 'SERVICO DE APOIO AS M E P EMPRESAS DE ALAGOAS-SEBRAE-AL',
             'telefone': None},
 'totais': {'desconto_condicionado': None,
            'desconto_incondicionado': None,
            'total_ibs_cbs': None,
            'total_retencoes_issqn_federais': '129.34',
            'valor_liquido_nfse': '1030.66',
            'valor_liquido_nfse_mais_ibs_cbs': None,
            'valor_operacao_servico': '1160.00'},
 'tributacao_federal': {'tipo_retencao_pis_cofins': '3',
                        'valor_cofins_debito_apuracao_propria': '34.80',
                        'valor_pis_debito_apuracao_propria': '7.54',
                        'valor_retencao_contribuicao_previdenciaria': None,
                        'valor_retencao_csll': '53.94',
                        'valor_retencao_irrf': '17.40'},
 'tributacao_ibs_cbs': None,
 'tributacao_municipal': {'aliquota_aplicada': '5.00',
                          'base_calculo_issqn': '1160.00',
                          'beneficio_municipal': None,
                          'deducoes_reducoes': None,
                          'desconto_incondicionado': None,
                          'local_incidencia': {'codigo_municipio': None,
                                               'codigo_pais_resultado': None,
                                               'local_incidencia_texto': 'Arapiraca',
                                               'municipio': 'Arapiraca',
                                               'pais': None,
                                               'uf': None},
                          'operacao_sujeita_issqn': True,
                          'regime_especial_tributacao_issqn': '0',
                          'retencao_issqn': '2',
                          'suspensao_exigibilidade': None,
                          'tipo_imunidade_issqn': None,
                          'tipo_tributacao_issqn': '1',
                          'valor_issqn_apurado': '58.00'},
 'valores_servico': {'desconto_condicionado': None, 'desconto_incondicionado': None, 'valor_servico': '1160.00'}})

EXPECTED_BY_FIXTURE = {
    "tests/fixtures/gov/nota_gov_1_29154166000144.xml": expected_nota_gov_1_29154166000144(),
    "tests/fixtures/gov/nota_gov_1_33762922000195.xml": expected_nota_gov_1_33762922000195(),
    "tests/fixtures/gov/nota_gov_1_39549075000161.xml": expected_nota_gov_1_39549075000161(),
    "tests/fixtures/gov/nota_gov_215_1750331400100.xml": expected_nota_gov_215_1750331400100(),
    "tests/fixtures/gov/nota_gov_2600000000196_17086031000100.xml": expected_nota_gov_2600000000196_17086031000100(),
    "tests/fixtures/gov/nota_gov_2600000000197_17086031000100.xml": expected_nota_gov_2600000000197_17086031000100(),
    "tests/fixtures/gov/nota_gov_2_39549075000161.xml": expected_nota_gov_2_39549075000161(),
    "tests/fixtures/gov/nota_gov_3_39549075000161.xml": expected_nota_gov_3_39549075000161(),
    "tests/fixtures/gov/nota_gov_439_01107244000130.xml": expected_nota_gov_439_01107244000130(),
    "tests/fixtures/gov/nota_gov_4578_16819228000148.xml": expected_nota_gov_4578_16819228000148(),
    "tests/fixtures/gov/nota_gov_4_39549075000161.xml": expected_nota_gov_4_39549075000161(),
}
